[package]
name = "quick_sort"
version = "0.1.0"
edition = "2021"
authors = ["Justin Luoma <justin@justinluoma.com>"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
